"""RORC (Royal Ocean Racing Club) race results scraper.

Scrapes IRC results from static HTML files hosted at:
  https://www.rorc.org/files/raceresults/{YYYY}/{filename}.html

Results are organized by year. Each year's index page lists links to
individual race result HTML files generated by Sail100 software.

No JavaScript required — pure HTTP + BeautifulSoup.
"""

import re
from datetime import date, datetime
from decimal import Decimal, InvalidOperation
from urllib.parse import urljoin

from bs4 import BeautifulSoup

from irc_data.scrapers.base import RateLimiter, fetch_with_retry, get_http_client
from irc_data.scrapers.result_base import EventRef, NormalizedResult, RaceResultSource

RORC_BASE = "https://www.rorc.org"
RESULTS_ARCHIVE = f"{RORC_BASE}/racing/results-archive"
RESULTS_FILE_BASE = f"{RORC_BASE}/files/raceresults"

rorc_limiter = RateLimiter(min_delay=2.0, jitter=1.0)

# Years with static HTML results (before SailRaceHQ migration)
RORC_YEARS = list(range(2007, 2023))


def _safe_decimal(val: str | None) -> Decimal | None:
    if not val:
        return None
    val = val.strip().replace("\xa0", "")
    if not val or val == "&nbsp;":
        return None
    try:
        return Decimal(val)
    except (InvalidOperation, ValueError):
        return None


def _parse_elapsed(val: str | None) -> str | None:
    """Parse RORC elapsed time format 'D - HH:MM:SS' to HH:MM:SS string."""
    if not val or val.strip() in ("", "&nbsp;", "\xa0"):
        return None
    val = val.strip()
    # Format: "1 - 14:49:54" (days - hours:min:sec) or just "14:49:54"
    m = re.match(r"(\d+)\s*-\s*(\d+):(\d+):(\d+)", val)
    if m:
        days, hours, mins, secs = int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4))
        total_hours = days * 24 + hours
        return f"{total_hours}:{mins:02d}:{secs:02d}"
    m = re.match(r"(\d+):(\d+):(\d+)", val)
    if m:
        return val.strip()
    return None


def _detect_status(comment: str | None) -> str:
    """Detect race status from RORC comments field."""
    if not comment:
        return "finished"
    comment = comment.strip().upper()
    if "DNF" in comment:
        return "DNF"
    if "DNS" in comment:
        return "DNS"
    if "DSQ" in comment:
        return "DSQ"
    if "OCS" in comment:
        return "OCS"
    if "RET" in comment:
        return "RET"
    return "finished"


def parse_rorc_result_html(html: str, event_name: str, source_url: str) -> list[NormalizedResult]:
    """Parse a RORC result HTML file into NormalizedResult objects."""
    soup = BeautifulSoup(html, "html.parser")
    results = []

    # Extract event title from h1/h2 tags
    h1_tags = soup.find_all("h1")
    h2_tags = soup.find_all("h2")

    race_title = event_name
    race_date = None
    for h1 in h1_tags:
        text = h1.get_text(strip=True)
        if text and "RORC" in text.upper() or "IRC" in text.upper() or len(text) > 10:
            race_title = text
            break

    for h2 in h2_tags:
        text = h2.get_text(strip=True)
        if "Start:" in text:
            date_str = text.replace("Start:", "").strip()
            for fmt in ["%a %d %b %y", "%a %d %b %Y", "%d %b %y", "%d %b %Y"]:
                try:
                    race_date = datetime.strptime(date_str, fmt).date()
                    break
                except ValueError:
                    continue

    # Find the results table (border="1" distinguishes it from layout tables)
    tables = soup.find_all("table", {"border": "1"})
    if not tables:
        # Fallback: find any table with enough columns
        tables = soup.find_all("table")
        tables = [t for t in tables if len(t.find_all("tr")) > 2]

    for table in tables:
        rows = table.find_all("tr")
        if len(rows) < 2:
            continue

        # Parse header row
        header_cells = rows[0].find_all(["td", "th"])
        headers = [c.get_text(strip=True).lower().replace("\n", " ").replace("<br/>", " ") for c in header_cells]

        # Map columns by header text
        col_map = {}
        for i, h in enumerate(headers):
            if "sail" in h and "no" in h or h == "sail no":
                col_map["sail_no"] = i
            elif h in ("boat", "yacht", "boat name"):
                col_map["boat_name"] = i
            elif "type" in h and "boat" in h:
                col_map["boat_type"] = i
            elif h in ("owner",):
                col_map["owner"] = i
            elif "handicap" in h or h == "tcc" or h == "rating":
                col_map["handicap"] = i
            elif "elapsed" in h:
                col_map["elapsed"] = i
            elif "corrected" in h:
                col_map["corrected"] = i
            elif "finish" in h and "place" in h:
                col_map["place"] = i
            elif h in ("place", "pos", "position"):
                col_map["place"] = i
            elif "comment" in h:
                col_map["comments"] = i
            elif "finish" in h and "time" in h:
                col_map["finish_time"] = i

        if "boat_name" not in col_map:
            continue

        # Parse data rows
        for row in rows[1:]:
            cells = row.find_all("td")
            if len(cells) < len(headers):
                continue

            def cell_text(key):
                idx = col_map.get(key)
                if idx is not None and idx < len(cells):
                    return cells[idx].get_text(strip=True)
                return None

            boat_name = cell_text("boat_name")
            if not boat_name:
                continue

            sail_no = cell_text("sail_no")
            handicap = _safe_decimal(cell_text("handicap"))
            place_str = cell_text("place")
            elapsed = _parse_elapsed(cell_text("elapsed"))
            corrected = _parse_elapsed(cell_text("corrected"))
            comments = cell_text("comments")
            boat_type = cell_text("boat_type")
            owner = cell_text("owner")

            place = None
            if place_str:
                try:
                    place = int(re.sub(r"[^\d]", "", place_str))
                except ValueError:
                    pass

            status = _detect_status(comments)

            results.append(NormalizedResult(
                boat_name=boat_name,
                sail_number=sail_no,
                event_name=race_title,
                event_date=race_date,
                event_series=event_name,
                organizing_club="RORC",
                event_type="offshore",
                place=place,
                fleet_size=len(rows) - 1,
                status=status,
                rating_type="irc_tcc" if handicap else None,
                rating_value=handicap,
                elapsed_time=elapsed,
                corrected_time=corrected,
                source_url=source_url,
                raw_data={
                    "boat_type": boat_type,
                    "owner": owner,
                    "comments": comments,
                    "headers": headers,
                },
            ))

    return results


class RORCSource(RaceResultSource):
    """RORC race results source."""

    def source_name(self) -> str:
        return "rorc"

    async def discover_events(self, since: date | None = None) -> list[EventRef]:
        """Discover RORC result files by scanning year index pages."""
        events = []
        min_year = since.year if since else 2007

        async with get_http_client() as client:
            for year in RORC_YEARS:
                if year < min_year:
                    continue

                year_url = f"{RORC_BASE}/racing/race-results/{year}-results"
                try:
                    await rorc_limiter.wait()
                    resp = await client.get(year_url)
                    if resp.status_code != 200:
                        continue

                    soup = BeautifulSoup(resp.text, "html.parser")
                    links = soup.find_all("a", href=re.compile(r"/files/raceresults/"))

                    for link in links:
                        href = link.get("href", "")
                        text = link.get_text(strip=True)
                        full_url = urljoin(RORC_BASE, href)

                        # Skip cumulative/season results (we want per-race)
                        filename = href.split("/")[-1] if "/" in href else href
                        if filename.endswith("os.html"):
                            continue

                        events.append(EventRef(
                            source="rorc",
                            event_name=f"{year} RORC - {text}" if text else f"{year} RORC - {filename}",
                            event_url=full_url,
                            organizing_club="RORC",
                            event_type="offshore",
                            metadata={"year": year, "filename": filename},
                        ))

                    print(f"  {year}: {len([e for e in events if e.metadata and e.metadata.get('year') == year])} result files")

                except Exception as e:
                    print(f"  {year}: error - {e}")

        return events

    async def scrape_event(self, ref: EventRef) -> list[NormalizedResult]:
        """Fetch and parse a single RORC result file."""
        async with get_http_client() as client:
            await rorc_limiter.wait()
            resp = await client.get(ref.event_url)
            if resp.status_code != 200:
                return []

            return parse_rorc_result_html(resp.text, ref.event_name, ref.event_url)
