import { chromium } from 'playwright';
const url = process.argv[2] || 'https://dev.sailratings.com/';
const out = process.argv[3] || '/tmp/cur.png';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
await page.goto(url, { waitUntil: 'networkidle', timeout: 30000 });
await page.waitForTimeout(800);
await page.screenshot({ path: out, fullPage: true });
console.log('OK', out, 'title=', await page.title());
await browser.close();
