"""Identity candidate and match-decision contracts (DP-04-01).

Goal: **make entity resolution explainable and reversible.**

This module is the *code of record* for how the platform talks about
"these two entities might be the same thing" and what it decided to do
about it.  It defines two immutable, JSON-round-trippable contracts:

* :class:`CandidatePairV1` — one *identity candidate*: a pair of canonical
  entities (DP-03-01 opaque ids) that blocking/scoring flagged as
  potential duplicates, together with the **features** that were compared,
  the **score**, and the **model/rule version** that produced it.
* :class:`MatchDecisionV1` — one *match decision* about a candidate pair:
  the **decision** (``match`` | ``non_match`` | ``uncertain`` | ``split``),
  the **actor** that decided (auto rule, model version, or human steward),
  the **threshold/policy** the decision was taken under, the **evidence**
  it rests on, the **timestamp**, and the **supersession** chain that
  makes every decision reversible without deleting anything.

Design invariants
-----------------

1. **No merge without stored evidence and threshold/policy.**
   :func:`apply_decision` is the only sanctioned bridge from a decision
   to the entity registry.  It refuses to merge unless the decision
   carries at least one :class:`EvidenceRef` *and* a non-empty
   ``threshold_policy``, and it *also* mechanically re-checks auto-rule
   scores against the named :class:`MatchPolicy`'s merge threshold — a
   decision that says "match" but whose score is below the policy's
   threshold is rejected, so the gate cannot be bypassed by asserting a
   verdict without the numbers to back it.

2. **Decisions are never mutated or deleted.**  A wrong decision is
   corrected by appending a *new* decision whose ``supersedes`` pointer
   names the old one (:func:`reverse_decision` / ``MatchJournal.reverse``).
   The old row stays in the journal with its ``superseded_by`` link —
   exactly the DP-03-02 assertion supersession semantics, lifted one
   level up from facts to identity decisions.

3. **Reversal never deletes source assertions.**  Reversing a merge uses
   the entity registry's :meth:`DomainModel.split`, which moves the
   *named* assertion references onto a resurrected entity stamped
   ``split_from``.  The original ``AssertionV1`` rows are re-keyed, not
   deleted (they remain content-addressed and immutable per DP-03-02),
   and the registry's append-only ``RegistryEvent`` log keeps both the
   merge and the split, so the pre-decision state is reconstructable for
   any system time.

4. **Everything is explainable.**  A decision answers, from its own
   fields alone: *which two entities* (``candidate.left_id`` /
   ``right_id``), *why they were compared* (``candidate.features``),
   *how strongly the evidence pointed* (``candidate.score`` and the
   feature weights), *under which logic* (``candidate.model_version`` /
   ``rule_version``), *who decided* (``actor``), *when* (``decided_at``),
   *under which policy* (``threshold_policy``), *on what evidence*
   (``evidence``), and *what became of the decision* (``superseded_by`` /
   ``reversal_of``).

Downstream handoff
------------------

* The **matching engine** (``irc_data.matching``) emits
  :class:`CandidatePairV1` records; it never merges.
* The **auto-decider / steward UI** turns candidates into
  :class:`MatchDecisionV1` records via :func:`decide` (which validates
  against a :class:`MatchPolicy`).
* The **registry bridge** calls :func:`apply_decision`; uncertainty is
  never a merge, ``split`` decisions require ``split_assertion_ids``.
* The **journal** (:class:`MatchJournal`) is the append-only store;
  ``decision_as_of(t)`` reproduces the effective decision state for any
  prior system time.
"""

from __future__ import annotations

import enum
import hashlib
import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Iterable, Mapping

# ---------------------------------------------------------------------------
# Schema version
# ---------------------------------------------------------------------------

#: Version tag embedded in every serialised candidate and decision.
SCHEMA_VERSION = "match-decision-v1"


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class CandidateStatus(str, enum.Enum):
    """Lifecycle of an identity candidate pair.

    ``OPEN``
        Generated by blocking/scoring, awaiting a decision.
    ``DECIDED``
        A current (non-superseded) decision exists for this pair.
    ``SUPERSEDED``
        The decision this candidate was decided by has itself been
        superseded — the pair is back in limbo (or re-decided by the
        successor decision, which references the same pair).
    """

    OPEN = "open"
    DECIDED = "decided"
    SUPERSEDED = "superseded"


class DecisionType(str, enum.Enum):
    """The four verdicts a match decision can record.

    ``MATCH``
        The two entities are the same real-world thing; the registry may
        merge them (subject to the evidence + policy gate).
    ``NON_MATCH``
        The two entities are distinct; the registry must keep them
        separate.  Stored so a future candidate generator can see the
        pair was *considered and rejected* (and by whom, on what
        evidence) instead of silently re-merging.
    ``UNCERTAIN``
        Neither match nor non-match could be justified under policy.
        Never merges; routes the pair to human review.
    ``SPLIT``
        The entities are *currently one* (previously merged, or one
        entity double-counting two real-world things) and must be split
        apart.  Carries ``split_assertion_ids`` naming exactly which
        assertion references move to the resurrected entity.
    """

    MATCH = "match"
    NON_MATCH = "non_match"
    UNCERTAIN = "uncertain"
    SPLIT = "split"


class ActorKind(str, enum.Enum):
    """Who (or what) took a match decision."""

    #: A deterministic rule (``rule_version`` identifies which).
    AUTO_RULE = "auto_rule"
    #: A statistical/ML model (``model_version`` identifies which).
    MODEL = "model"
    #: A human steward (``actor`` carries the steward's id/name).
    HUMAN = "human"


#: Allowed decision strings (mirrors any future DB check constraint).
DECISIONS: tuple[str, ...] = tuple(d.value for d in DecisionType)


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class MatchDecisionError(ValueError):
    """Base class for match-contract violations."""


class MissingEvidenceError(MatchDecisionError):
    """A merge was attempted without stored evidence."""


class MissingPolicyError(MatchDecisionError):
    """A decision was taken without naming its threshold/policy."""


class BelowThresholdError(MatchDecisionError):
    """An auto/rule ``match`` decision's score is below the policy threshold."""


class DecisionStateError(MatchDecisionError):
    """The decision cannot be applied/reversed in the journal's state."""


# ---------------------------------------------------------------------------
# Helpers (same conventions as irc_data.assertions.models)
# ---------------------------------------------------------------------------


def _utc(dt: datetime) -> datetime:
    """Normalise a datetime to aware-UTC (naive assumed UTC)."""
    if dt.tzinfo is None:
        return dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def _dt_to_iso(dt: datetime | None) -> str | None:
    if dt is None:
        return None
    return _utc(dt).isoformat()


def _dt_from_iso(s: str | datetime | None) -> datetime | None:
    if s is None:
        return None
    if isinstance(s, datetime):
        return _utc(s)
    return _utc(datetime.fromisoformat(s))


def _canonical_json(payload: Any) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)


def _content_id(prefix: str, payload: Mapping[str, Any]) -> str:
    """Deterministic content-addressed id: ``<prefix>_<sha256[:24]>``."""
    digest = hashlib.sha256(_canonical_json(payload).encode("utf-8")).hexdigest()
    return f"{prefix}_{digest[:24]}"


# ---------------------------------------------------------------------------
# Features, evidence, policy
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class FeatureScoreV1:
    """One compared attribute of a candidate pair.

    Features are the *explainability payload*: each names the attribute
    compared (``sail_number``, ``boat_name``, ``design`` …), the two
    observed values, the similarity computed, and the weight that
    similarity carried in the pair's aggregate score.
    """

    name: str
    value_left: Any = None
    value_right: Any = None
    #: Similarity in [0, 1]; ``None`` means "not comparable / missing data".
    similarity: float | None = None
    #: Non-negative weight this feature contributed to the aggregate score.
    weight: float = 0.0

    def __post_init__(self) -> None:
        if not self.name:
            raise MatchDecisionError("feature name is required")
        if self.similarity is not None and not (0.0 <= float(self.similarity) <= 1.0):
            raise MatchDecisionError(
                f"feature {self.name!r}: similarity must be in [0, 1], "
                f"got {self.similarity!r}"
            )
        if float(self.weight) < 0.0:
            raise MatchDecisionError(
                f"feature {self.name!r}: weight must be >= 0, got {self.weight!r}"
            )

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "value_left": self.value_left,
            "value_right": self.value_right,
            "similarity": self.similarity,
            "weight": float(self.weight),
        }

    @classmethod
    def from_dict(cls, d: Mapping[str, Any]) -> "FeatureScoreV1":
        return cls(
            name=d["name"],
            value_left=d.get("value_left"),
            value_right=d.get("value_right"),
            similarity=d.get("similarity"),
            weight=float(d.get("weight", 0.0)),
        )


@dataclass(frozen=True)
class EvidenceRef:
    """A pointer to one piece of evidence a decision rests on.

    ``kind`` names the evidence class: ``assertion`` (a DP-03-02
    ``AssertionV1`` id), ``artifact`` (a DP-02-01 raw provenance
    envelope hash), ``registry_event`` (a prior merge/split log entry),
    ``certificate_ref`` / ``results_url`` … — free-form but required.
    ``ref`` is the id, hash or URL.  ``note`` records *why* the evidence
    supports the decision, so a reviewer never has to guess.
    """

    kind: str
    ref: str
    note: str = ""

    def __post_init__(self) -> None:
        if not self.kind:
            raise MatchDecisionError("evidence kind is required")
        if not self.ref:
            raise MatchDecisionError("evidence ref is required")

    def to_dict(self) -> dict[str, Any]:
        return {"kind": self.kind, "ref": self.ref, "note": self.note}

    @classmethod
    def from_dict(cls, d: Mapping[str, Any]) -> "EvidenceRef":
        return cls(kind=d["kind"], ref=d["ref"], note=d.get("note", ""))


@dataclass(frozen=True)
class MatchPolicy:
    """The threshold policy under which decisions are judged.

    A policy is *named and versioned* (``name``) so every decision can
    point at the exact rulebook it was taken under; when thresholds are
    tuned, the name changes and history stays attributable.

    ``merge_threshold``
        Minimum aggregate score for an auto/rule ``match`` to be
        **applied** as a merge.  Decisions at or above this score are
        auto-mergeable; below it, a claimed ``match`` from an auto actor
        is rejected at the gate.
    ``review_threshold``
        Floor of the *uncertain* band: scores in
        ``[review_threshold, merge_threshold)`` route to human review.
    ``non_match_threshold``
        Scores below this are auto-``non_match``-able.
    """

    name: str
    merge_threshold: float
    review_threshold: float = 0.0
    non_match_threshold: float = 0.0

    def __post_init__(self) -> None:
        if not self.name:
            raise MatchDecisionError("policy name is required")
        for label, v in (
            ("merge_threshold", self.merge_threshold),
            ("review_threshold", self.review_threshold),
            ("non_match_threshold", self.non_match_threshold),
        ):
            if not (0.0 <= float(v) <= 1.0):
                raise MatchDecisionError(f"{label} must be in [0, 1], got {v!r}")
        if not (self.non_match_threshold <= self.review_threshold <= self.merge_threshold):
            raise MatchDecisionError(
                "thresholds must satisfy "
                "non_match_threshold <= review_threshold <= merge_threshold"
            )

    # -- Verdict helpers ------------------------------------------------------

    def band_for_score(self, score: float) -> DecisionType:
        """The verdict band a bare score falls into under this policy."""
        if score >= self.merge_threshold:
            return DecisionType.MATCH
        if score < self.non_match_threshold:
            return DecisionType.NON_MATCH
        return DecisionType.UNCERTAIN

    def permits_auto_merge(self, score: float) -> bool:
        return score >= self.merge_threshold

    def permits_auto_non_match(self, score: float) -> bool:
        return score < self.non_match_threshold

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "merge_threshold": float(self.merge_threshold),
            "review_threshold": float(self.review_threshold),
            "non_match_threshold": float(self.non_match_threshold),
        }

    @classmethod
    def from_dict(cls, d: Mapping[str, Any]) -> "MatchPolicy":
        return cls(
            name=d["name"],
            merge_threshold=float(d["merge_threshold"]),
            review_threshold=float(d.get("review_threshold", 0.0)),
            non_match_threshold=float(d.get("non_match_threshold", 0.0)),
        )


#: The platform's default boat-identity policy.  Named + versioned; tuning
#: any threshold means minting a new name so history stays attributable.
DEFAULT_BOAT_POLICY = MatchPolicy(
    name="boat-merge-policy-v1",
    merge_threshold=0.90,
    review_threshold=0.50,
    non_match_threshold=0.20,
)


# ---------------------------------------------------------------------------
# CandidatePairV1
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CandidatePairV1:
    """One identity candidate: two canonical entities flagged as possible
    duplicates, with the full explanation of *why*.

    ``left_id`` / ``right_id``
        DP-03-01 opaque entity ids (``boat_01J4Z…``).  The pair key is
        normalised order-independently, so the pair (A, B) and (B, A) are
        the same candidate.
    ``features``
        The compared attributes — the human-readable justification.
    ``score``
        Aggregate similarity in [0, 1].
    ``model_version`` / ``rule_version``
        Exactly which scorer/blocker produced this candidate.  At least
        one must be set: a candidate with no version is unexplained.
    """

    entity_type: str
    left_id: str
    right_id: str
    features: tuple[FeatureScoreV1, ...] = ()
    score: float = 0.0
    model_version: str | None = None
    rule_version: str | None = None
    generated_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    status: str = CandidateStatus.OPEN.value
    metadata: dict[str, Any] = field(default_factory=dict)
    candidate_id: str = ""
    schema_version: str = SCHEMA_VERSION

    def __post_init__(self) -> None:
        if not self.entity_type:
            raise MatchDecisionError("entity_type is required")
        if not self.left_id or not self.right_id:
            raise MatchDecisionError("both left_id and right_id are required")
        if self.left_id == self.right_id:
            raise MatchDecisionError("a candidate pair must reference two distinct entities")
        if not (0.0 <= float(self.score) <= 1.0):
            raise MatchDecisionError(f"score must be in [0, 1], got {self.score!r}")
        if not self.model_version and not self.rule_version:
            raise MatchDecisionError(
                "a candidate must name its model_version and/or rule_version — "
                "an unexplained candidate is not actionable"
            )
        object.__setattr__(self, "generated_at", _utc(self.generated_at))
        object.__setattr__(self, "features", tuple(self.features))
        if not self.candidate_id:
            object.__setattr__(self, "candidate_id", self._derive_id())

    # -- Identity --------------------------------------------------------------

    @property
    def pair_key(self) -> tuple[str, str]:
        """Order-independent key so (A, B) ≡ (B, A)."""
        return tuple(sorted((self.left_id, self.right_id)))  # type: ignore[return-value]

    def _derive_id(self) -> str:
        return _content_id(
            "cand",
            {
                "schema_version": self.schema_version,
                "entity_type": self.entity_type,
                "pair_key": self.pair_key,
                "score": float(self.score),
                "features": [f.to_dict() for f in self.features],
                "model_version": self.model_version,
                "rule_version": self.rule_version,
                "generated_at": _dt_to_iso(self.generated_at),
            },
        )

    # -- Serialisation ---------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "candidate_id": self.candidate_id,
            "entity_type": self.entity_type,
            "left_id": self.left_id,
            "right_id": self.right_id,
            "pair_key": list(self.pair_key),
            "features": [f.to_dict() for f in self.features],
            "score": float(self.score),
            "model_version": self.model_version,
            "rule_version": self.rule_version,
            "generated_at": _dt_to_iso(self.generated_at),
            "status": self.status,
            "metadata": self.metadata or {},
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), sort_keys=True)

    @classmethod
    def from_dict(cls, d: Mapping[str, Any]) -> "CandidatePairV1":
        return cls(
            schema_version=d.get("schema_version", SCHEMA_VERSION),
            candidate_id=d.get("candidate_id", ""),
            entity_type=d["entity_type"],
            left_id=d["left_id"],
            right_id=d["right_id"],
            features=tuple(FeatureScoreV1.from_dict(f) for f in d.get("features", ())),
            score=float(d.get("score", 0.0)),
            model_version=d.get("model_version"),
            rule_version=d.get("rule_version"),
            generated_at=_dt_from_iso(d["generated_at"]) if d.get("generated_at") else datetime.now(timezone.utc),
            status=d.get("status", CandidateStatus.OPEN.value),
            metadata=dict(d.get("metadata") or {}),
        )

    @classmethod
    def from_json(cls, s: str) -> "CandidatePairV1":
        return cls.from_dict(json.loads(s))


# ---------------------------------------------------------------------------
# MatchDecisionV1
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class MatchDecisionV1:
    """One immutable match decision about a candidate pair.

    Frozen: a decision, once recorded, never changes.  Correction is a
    *new* decision with ``supersedes`` pointing here (and
    ``reversal_of`` when the new decision undoes this one); this row
    gains a ``superseded_by`` link via :meth:`superseded`.
    """

    candidate: CandidatePairV1
    decision: str
    actor: str
    actor_kind: str
    threshold_policy: str
    evidence: tuple[EvidenceRef, ...] = ()
    decided_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    rationale: str = ""
    #: Assertion ids to move when ``decision == "split"``.
    split_assertion_ids: tuple[str, ...] = ()
    #: Supersession / reversal chain.
    supersedes: str | None = None
    superseded_by: str | None = None
    superseded_at: datetime | None = None
    reversal_of: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    id: str = ""
    schema_version: str = SCHEMA_VERSION

    def __post_init__(self) -> None:
        if self.decision not in DECISIONS:
            raise MatchDecisionError(
                f"decision must be one of {DECISIONS}, got {self.decision!r}"
            )
        if not self.actor:
            raise MatchDecisionError("actor is required — a decision must name who took it")
        if self.actor_kind not in tuple(a.value for a in ActorKind):
            raise MatchDecisionError(
                f"actor_kind must be one of {[a.value for a in ActorKind]}, "
                f"got {self.actor_kind!r}"
            )
        if not self.threshold_policy:
            raise MissingPolicyError(
                "threshold_policy is required — no decision is taken outside a policy"
            )
        if self.decision == DecisionType.SPLIT.value and not self.split_assertion_ids:
            raise MatchDecisionError(
                "a split decision must name split_assertion_ids — the registry "
                "needs to know exactly which assertion references move"
            )
        object.__setattr__(self, "decided_at", _utc(self.decided_at))
        if self.superseded_at is not None:
            object.__setattr__(self, "superseded_at", _utc(self.superseded_at))
        object.__setattr__(self, "evidence", tuple(self.evidence))
        object.__setattr__(self, "split_assertion_ids", tuple(self.split_assertion_ids))
        if not self.id:
            object.__setattr__(self, "id", self._derive_id())

    # -- Identity --------------------------------------------------------------

    def _derive_id(self) -> str:
        return _content_id(
            "dec",
            {
                "schema_version": self.schema_version,
                "candidate_id": self.candidate.candidate_id,
                "decision": self.decision,
                "actor": self.actor,
                "actor_kind": self.actor_kind,
                "threshold_policy": self.threshold_policy,
                "decided_at": _dt_to_iso(self.decided_at),
                "supersedes": self.supersedes,
                "reversal_of": self.reversal_of,
                "split_assertion_ids": list(self.split_assertion_ids),
                "evidence": [e.to_dict() for e in self.evidence],
            },
        )

    # -- State predicates --------------------------------------------------------

    @property
    def is_superseded(self) -> bool:
        return self.superseded_by is not None

    def known_at(self, as_of: datetime) -> bool:
        """True if the system knew of this decision at system time *as_of*."""
        return self.decided_at <= _utc(as_of)

    # -- Supersession ------------------------------------------------------------

    def superseded(self, successor: "MatchDecisionV1") -> "MatchDecisionV1":
        """Return a copy marked superseded by *successor* (bitemporal).

        The successor must point back via ``supersedes``.  ``superseded_at``
        is the successor's ``decided_at``, so a supersession only affects
        as-of views at or after the time the successor was decided — the
        view *before* the correction still shows this decision in force.
        """
        if successor.id == self.id:
            raise MatchDecisionError("a decision cannot supersede itself")
        if successor.supersedes != self.id:
            raise MatchDecisionError(
                "successor.supersedes must point at this decision's id"
            )
        return self._replace(
            superseded_by=successor.id,
            superseded_at=successor.decided_at,
        )

    def _replace(self, **changes: Any) -> "MatchDecisionV1":
        """frozen-dataclass replace that keeps the original decision id."""
        payload = self.to_dict()
        payload.update(changes)
        payload["decision_id"] = self.id  # id is identity, not content
        return MatchDecisionV1.from_dict(payload)

    # -- Serialisation ---------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "decision_id": self.id,
            "candidate": self.candidate.to_dict(),
            "decision": self.decision,
            "actor": self.actor,
            "actor_kind": self.actor_kind,
            "threshold_policy": self.threshold_policy,
            "evidence": [e.to_dict() for e in self.evidence],
            "decided_at": _dt_to_iso(self.decided_at),
            "rationale": self.rationale,
            "split_assertion_ids": list(self.split_assertion_ids),
            "supersedes": self.supersedes,
            "superseded_by": self.superseded_by,
            "superseded_at": _dt_to_iso(self.superseded_at),
            "reversal_of": self.reversal_of,
            "metadata": self.metadata or {},
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), sort_keys=True)

    @classmethod
    def from_dict(cls, d: Mapping[str, Any]) -> "MatchDecisionV1":
        return cls(
            schema_version=d.get("schema_version", SCHEMA_VERSION),
            id=d.get("decision_id", ""),
            candidate=CandidatePairV1.from_dict(d["candidate"]),
            decision=d["decision"],
            actor=d["actor"],
            actor_kind=d.get("actor_kind", ActorKind.AUTO_RULE.value),
            threshold_policy=d["threshold_policy"],
            evidence=tuple(EvidenceRef.from_dict(e) for e in d.get("evidence", ())),
            decided_at=_dt_from_iso(d["decided_at"]) if d.get("decided_at") else datetime.now(timezone.utc),
            rationale=d.get("rationale", ""),
            split_assertion_ids=tuple(d.get("split_assertion_ids") or ()),
            supersedes=d.get("supersedes"),
            superseded_by=d.get("superseded_by"),
            superseded_at=_dt_from_iso(d.get("superseded_at")),
            reversal_of=d.get("reversal_of"),
            metadata=dict(d.get("metadata") or {}),
        )

    @classmethod
    def from_json(cls, s: str) -> "MatchDecisionV1":
        return cls.from_dict(json.loads(s))


# ---------------------------------------------------------------------------
# decide() — build + validate a decision against a policy
# ---------------------------------------------------------------------------


def decide(
    candidate: CandidatePairV1,
    decision: DecisionType | str,
    *,
    actor: str,
    actor_kind: ActorKind | str,
    policy: MatchPolicy,
    evidence: Iterable[EvidenceRef] = (),
    decided_at: datetime | None = None,
    rationale: str = "",
    split_assertion_ids: Iterable[str] = (),
    supersedes: str | None = None,
    reversal_of: str | None = None,
    metadata: Mapping[str, Any] | None = None,
) -> MatchDecisionV1:
    """Create a :class:`MatchDecisionV1`, enforcing the decision contract.

    Validation rules (this is where policy meets the decision):

    * Every decision names its policy (``policy.name`` is stored as
      ``threshold_policy``).
    * An auto (rule/model) ``match`` whose candidate score is below
      ``policy.merge_threshold`` is rejected — a verdict cannot outrun
      the numbers under its own policy.  Human stewards may decide over
      the band, but the evidence requirement below still applies at the
      merge gate.
    * An auto ``non_match`` above ``policy.merge_threshold`` is rejected
      (symmetric sanity: the rule contradicts its own score).
    * ``split`` decisions must name ``split_assertion_ids`` (enforced by
      the dataclass as well).
    """
    decision_value = decision.value if isinstance(decision, DecisionType) else decision
    actor_kind_value = actor_kind.value if isinstance(actor_kind, ActorKind) else actor_kind

    if actor_kind_value in (ActorKind.AUTO_RULE.value, ActorKind.MODEL.value):
        if decision_value == DecisionType.MATCH.value and not policy.permits_auto_merge(
            candidate.score
        ):
            raise BelowThresholdError(
                f"auto match rejected: score {candidate.score:.3f} < "
                f"merge_threshold {policy.merge_threshold:.3f} of {policy.name!r}"
            )
        if decision_value == DecisionType.NON_MATCH.value and policy.permits_auto_merge(
            candidate.score
        ):
            raise BelowThresholdError(
                f"auto non_match rejected: score {candidate.score:.3f} >= "
                f"merge_threshold {policy.merge_threshold:.3f} of {policy.name!r}"
            )

    return MatchDecisionV1(
        candidate=candidate,
        decision=decision_value,
        actor=actor,
        actor_kind=actor_kind_value,
        threshold_policy=policy.name,
        evidence=tuple(evidence),
        decided_at=decided_at or datetime.now(timezone.utc),
        rationale=rationale,
        split_assertion_ids=tuple(split_assertion_ids),
        supersedes=supersedes,
        reversal_of=reversal_of,
        metadata=dict(metadata or {}),
    )


# ---------------------------------------------------------------------------
# The merge gate — no merge without stored evidence and threshold/policy
# ---------------------------------------------------------------------------


def _enforce_merge_gate(
    decision: MatchDecisionV1,
    policy: MatchPolicy | None,
) -> None:
    """Acceptance criterion, in code: *no merge occurs without stored
    evidence and threshold/policy*."""
    if not decision.evidence:
        raise MissingEvidenceError(
            f"merge of {decision.candidate.left_id!r} + "
            f"{decision.candidate.right_id!r} refused: the decision carries no "
            "stored evidence"
        )
    if not decision.threshold_policy:
        # MatchDecisionV1 already enforces this; kept explicit so the gate
        # reads as the acceptance criterion states it.
        raise MissingPolicyError("merge refused: no threshold/policy recorded")
    if policy is not None:
        if policy.name != decision.threshold_policy:
            raise MissingPolicyError(
                f"decision names policy {decision.threshold_policy!r} but was "
                f"applied under {policy.name!r}"
            )
        if decision.actor_kind in (ActorKind.AUTO_RULE.value, ActorKind.MODEL.value) and (
            not policy.permits_auto_merge(decision.candidate.score)
        ):
            raise BelowThresholdError(
                f"merge refused: score {decision.candidate.score:.3f} is below "
                f"{policy.name!r} merge threshold {policy.merge_threshold:.3f}"
            )


def apply_decision(
    model: "DomainModel",
    decision: MatchDecisionV1,
    *,
    policy: MatchPolicy | None = None,
    at: datetime | None = None,
):
    """Apply a recorded decision to the entity registry.

    This is the **only** sanctioned bridge from decisions to registry
    merges/splits:

    * ``match`` → :meth:`DomainModel.merge` — gated by
      :func:`_enforce_merge_gate` (evidence + policy + threshold).
      The lower-sorted (older-prefix is irrelevant; deterministic) id of
      the pair is the survivor by default, so application is
      reproducible.
    * ``split`` → :meth:`DomainModel.split` moving exactly
      ``decision.split_assertion_ids``.
    * ``non_match`` / ``uncertain`` → **no registry mutation** (returns
      ``None``); the decision itself is the deliverable.

    Returns the surviving entity for merges, the new entity for splits,
    and ``None`` otherwise.
    """
    # Local import: matching contracts sit *above* the entity registry.
    from irc_data.domain.entities import DomainModel  # noqa: F401

    when = _utc(at) if at else datetime.now(timezone.utc)

    if decision.decision == DecisionType.MATCH.value:
        _enforce_merge_gate(decision, policy)
        survivor_id, removed_id = decision.candidate.pair_key
        return model.merge(
            survivor_id,
            removed_id,
            at=when,
            reason=f"match decision {decision.id} ({decision.threshold_policy})",
        )

    if decision.decision == DecisionType.SPLIT.value:
        # Split the entity the named assertions currently live on.  For a
        # reversal that is normally the survivor of the merge being undone
        # (the decision candidate's other side); fall back to ``left_id``
        # for a first-time split of a never-merged entity.
        candidate_ids = set(decision.candidate.pair_key)
        holder_id = decision.candidate.left_id
        if decision.reversal_of is not None:
            # Undoing a merge: the assertions to move live on the *survivor*
            # of the merge.  Find the merged-away side and follow its
            # ``merged_into`` pointer to the survivor (bypassing the liveness
            # check — the removed entity is preserved precisely so this
            # audit trail remains reachable).
            survivor_id: str | None = None
            for eid in candidate_ids:
                entity = model.get(eid)  # no liveness filter on purpose
                if entity.merged_into:
                    survivor_id = entity.merged_into
                    break
            if survivor_id is not None:
                holder_id = survivor_id
            else:
                # No merge to undo on either side — prefer whichever side
                # actually holds the named assertions.
                wanted = set(decision.split_assertion_ids)
                for eid in candidate_ids:
                    entity = model.get(eid)
                    if wanted <= {ref.assertion_id for ref in entity.assertions}:
                        holder_id = eid
                        break
        new_entity = model.split(
            holder_id,
            assertion_ids=decision.split_assertion_ids,
            at=when,
            reason=f"split decision {decision.id} ({decision.threshold_policy})",
        )
        # Resurrection path: undoing a merge means the wrongly-merged hull
        # already *has* an entity (it was never deleted — only stamped
        # removed).  Transfer the split-off assertions onto it, clear its
        # removal, and discard the transient shell so the original id is
        # live again with full lineage.  The assertion rows themselves are
        # re-keyed (new content-addressed ids), never deleted — the same
        # information-preserving semantics as merge/split.
        if decision.reversal_of is not None:
            removed_id = next(
                (eid for eid in candidate_ids if eid != holder_id), None
            )
            removed = model.get(removed_id) if removed_id else None
            if removed is not None and removed.merged_into == holder_id:
                import dataclasses as _dc

                from irc_data.domain.entities import SourceAssertionRef

                for ref in list(new_entity.assertions):
                    assertion = model._assertions[ref.assertion_id]
                    rekeyed = _dc.replace(
                        assertion, entity_key=removed.entity_key, assertion_id=""
                    )
                    del model._assertions[ref.assertion_id]
                    model._assertions[rekeyed.assertion_id] = rekeyed
                    new_entity.assertions.remove(ref)
                    removed.assertions.append(
                        SourceAssertionRef(
                            assertion_id=rekeyed.assertion_id,
                            field=rekeyed.field,
                            recorded_at=rekeyed.recorded_at,
                            valid_from=rekeyed.valid_from,
                            source_slug=rekeyed.source_slug,
                        )
                    )
                removed.removed_at = None
                removed.merged_into = None
                removed.split_from = holder_id
                # Discard the transient shell so no orphan entity remains.
                del model._entities[new_entity.entity_id]
                return removed
        return new_entity

    # non_match / uncertain: explainable no-ops.  The stored decision is
    # what future candidate generators consult; the registry is untouched.
    return None


# ---------------------------------------------------------------------------
# Reversal — correction without deletion
# ---------------------------------------------------------------------------


def reverse_decision(
    original: MatchDecisionV1,
    *,
    actor: str,
    actor_kind: ActorKind | str,
    policy: MatchPolicy,
    evidence: Iterable[EvidenceRef] = (),
    decided_at: datetime | None = None,
    rationale: str = "",
    split_assertion_ids: Iterable[str] = (),
) -> MatchDecisionV1:
    """Build the decision that *reverses* ``original`` without deleting it.

    The reversal of a ``match`` is a ``split``; the reversal of a
    ``split`` or a ``non_match`` is a fresh ``match`` (re-asserting the
    pair) — which must itself pass :func:`decide`'s policy checks and the
    merge gate when applied.  Reversing an ``uncertain`` decision yields
    the corrected verdict the caller supplies via ``split_assertion_ids``
    semantics — by default a ``non_match``.

    The new decision carries ``supersedes=original.decision_id`` and
    ``reversal_of=original.decision_id``; :meth:`MatchJournal.record`
    stamps the original's ``superseded_by`` link.  Both rows live
    side-by-side in the journal — history is appended, never rewritten.
    """
    if original.decision == DecisionType.MATCH.value:
        verdict = DecisionType.SPLIT
    elif original.decision == DecisionType.UNCERTAIN.value:
        verdict = DecisionType.NON_MATCH
    else:  # non_match or split → re-assert the pair
        verdict = DecisionType.MATCH
    return decide(
        original.candidate,
        verdict,
        actor=actor,
        actor_kind=actor_kind,
        policy=policy,
        evidence=evidence,
        decided_at=decided_at,
        rationale=rationale or f"reversal of {original.id}",
        split_assertion_ids=split_assertion_ids,
        supersedes=original.id,
        reversal_of=original.id,
    )


# ---------------------------------------------------------------------------
# MatchJournal — the append-only decision store
# ---------------------------------------------------------------------------


class MatchJournal:
    """Append-only, in-memory journal of candidates and match decisions.

    Persistence rows can be produced with :meth:`snapshot`; the journal
    semantics mirror the DP-03-02 assertion store:

    * decisions are immutable once recorded;
    * supersession is bitemporal — :meth:`decision_as_of` reproduces the
      effective verdict for any prior system time;
    * nothing is ever deleted, so every merge is reversible by appending
      a reversal decision and applying it.
    """

    def __init__(self) -> None:
        self._candidates: dict[str, CandidatePairV1] = {}
        self._decisions: dict[str, MatchDecisionV1] = {}
        #: candidate_id → ordered decision ids (the supersession chain).
        self._chain: dict[str, list[str]] = {}

    # -- Recording ---------------------------------------------------------------

    def record_candidate(self, candidate: CandidatePairV1) -> str:
        self._candidates[candidate.candidate_id] = candidate
        return candidate.candidate_id

    def record(self, decision: MatchDecisionV1) -> str:
        """Append a decision, linking any superseded predecessor."""
        cid = decision.candidate.candidate_id
        if decision.candidate.candidate_id not in self._candidates:
            self.record_candidate(decision.candidate)
        if decision.supersedes:
            prev = self._decisions.get(decision.supersedes)
            if prev is None:
                raise DecisionStateError(
                    f"superseded decision {decision.supersedes!r} is not in the journal"
                )
            self._decisions[prev.id] = prev.superseded(decision)
        self._decisions[decision.id] = decision
        self._chain.setdefault(cid, []).append(decision.id)
        return decision.id

    def reverse(
        self,
        decision_id: str,
        *,
        actor: str,
        actor_kind: ActorKind | str,
        policy: MatchPolicy,
        evidence: Iterable[EvidenceRef] = (),
        decided_at: datetime | None = None,
        rationale: str = "",
        split_assertion_ids: Iterable[str] = (),
    ) -> MatchDecisionV1:
        """Append (and return) the reversal of a recorded decision."""
        original = self._decisions[decision_id]
        if original.is_superseded:
            raise DecisionStateError(
                f"decision {decision_id!r} is already superseded by "
                f"{original.superseded_by!r}"
            )
        reversal = reverse_decision(
            original,
            actor=actor,
            actor_kind=actor_kind,
            policy=policy,
            evidence=evidence,
            decided_at=decided_at,
            rationale=rationale,
            split_assertion_ids=split_assertion_ids,
        )
        self.record(reversal)
        return reversal

    # -- Queries -----------------------------------------------------------------

    def get(self, decision_id: str) -> MatchDecisionV1:
        return self._decisions[decision_id]

    def candidate(self, candidate_id: str) -> CandidatePairV1:
        return self._candidates[candidate_id]

    def decisions_for(self, candidate_id: str) -> tuple[MatchDecisionV1, ...]:
        """The full supersession chain for one candidate, oldest first."""
        return tuple(self._decisions[i] for i in self._chain.get(candidate_id, ()))

    def current_decision(
        self, candidate_id: str, *, as_of: datetime | None = None
    ) -> MatchDecisionV1 | None:
        """The decision currently in force for a candidate.

        With ``as_of``, reproduces what was in force at that system time:
        only decisions with ``decided_at <= as_of`` are known, and a
        supersession counts only once ``superseded_at <= as_of`` — so a
        later correction never rewrites the past.
        """
        when = _utc(as_of) if as_of else None
        chain = self._chain.get(candidate_id, ())
        current: MatchDecisionV1 | None = None
        for did in chain:
            d = self._decisions[did]
            if when is not None and not d.known_at(when):
                continue
            current = d
        # Walk back through supersessions that were already in force at
        # ``when``: the last *known* decision whose supersession was *not
        # yet* in force is the effective one.
        if when is not None:
            for did in chain:
                d = self._decisions[did]
                if not d.known_at(when):
                    break
                if d.superseded_at is not None and d.superseded_at <= when:
                    continue  # superseded by then — keep walking
                return d
        return current

    def open_candidates(self) -> tuple[CandidatePairV1, ...]:
        """Candidates with no current decision (the review queue)."""
        return tuple(
            c
            for cid, c in self._candidates.items()
            if self.current_decision(cid) is None
        )

    # -- Persistence ---------------------------------------------------------------

    def snapshot(self) -> dict[str, Any]:
        """Serialise the journal (candidates + full decision chains)."""
        return {
            "schema_version": SCHEMA_VERSION,
            "candidates": [c.to_dict() for c in self._candidates.values()],
            "decisions": [d.to_dict() for d in self._decisions.values()],
            "chains": {cid: list(ids) for cid, ids in self._chain.items()},
        }


__all__ = [
    "ActorKind",
    "BelowThresholdError",
    "CandidatePairV1",
    "CandidateStatus",
    "DecisionStateError",
    "DecisionType",
    "DECISIONS",
    "DEFAULT_BOAT_POLICY",
    "EvidenceRef",
    "FeatureScoreV1",
    "MatchDecisionError",
    "MatchDecisionV1",
    "MatchJournal",
    "MatchPolicy",
    "MissingEvidenceError",
    "MissingPolicyError",
    "SCHEMA_VERSION",
    "apply_decision",
    "decide",
    "reverse_decision",
]
